<section id="viewing" class="bg-surface-low py-16 lg:py-24">
    <div class="mx-auto grid max-w-[1360px] gap-10 px-5 lg:grid-cols-12 lg:px-16">
        <div class="lg:col-span-5"><p class="text-xs font-bold uppercase tracking-[0.16em] text-secondary">Schedule a Visit</p><h2 class="mt-2 font-display text-4xl font-medium leading-tight text-primary">Come See Your Future Home</h2><p class="mt-4 text-base leading-7 text-copy">Explore the featured home concepts and experience how a residential viewing experience could be presented.</p><div class="mt-7 space-y-5 rounded-2xl bg-surface p-6 shadow-sm"><div class="flex gap-3"><span class="material-symbols-outlined text-secondary" aria-hidden="true">event_available</span><p><strong class="block text-sm text-primary">Conceptual Tour Overview</strong><span class="text-sm leading-6 text-copy">Explore the featured home concepts through this portfolio demonstration.</span></p></div><div class="flex gap-3"><span class="material-symbols-outlined text-secondary" aria-hidden="true">info</span><p><strong class="block text-sm text-primary">Conceptual Advisory</strong><span class="text-sm leading-6 text-copy">Property details in a real project would be provided and verified by the actual developer.</span></p></div></div></div>
        <div class="lg:col-span-7"><div class="rounded-3xl bg-surface p-6 shadow-[0_16px_36px_-8px_rgba(30,58,43,0.16)] sm:p-10">
            @if (session('viewing_success'))<div class="mb-6 flex gap-3 rounded-xl bg-secondary-container p-4 text-sm text-primary" role="status"><span class="material-symbols-outlined" aria-hidden="true">check_circle</span><p>{{ session('viewing_success') }}</p></div>@endif
            <form method="POST" action="{{ route('viewing-request.store') }}" class="space-y-5" novalidate data-viewing-form>
                @csrf
                <div class="grid gap-5 sm:grid-cols-2">
                    <div><label for="full_name" class="field-label">Full Name <span aria-hidden="true">*</span></label><input id="full_name" name="full_name" type="text" value="{{ old('full_name') }}" autocomplete="name" required class="field-input @error('full_name') field-input-error @enderror" @error('full_name') aria-invalid="true" aria-describedby="full_name_error" @enderror>@error('full_name')<p id="full_name_error" class="field-error" role="alert">{{ $message }}</p>@enderror</div>
                    <div><label for="mobile_number" class="field-label">Mobile Number <span aria-hidden="true">*</span></label><input id="mobile_number" name="mobile_number" type="tel" value="{{ old('mobile_number') }}" autocomplete="tel" required class="field-input @error('mobile_number') field-input-error @enderror" @error('mobile_number') aria-invalid="true" aria-describedby="mobile_number_error" @enderror>@error('mobile_number')<p id="mobile_number_error" class="field-error" role="alert">{{ $message }}</p>@enderror</div>
                </div>
                <div class="grid gap-5 sm:grid-cols-2">
                    <div><label for="email" class="field-label">Email Address <span aria-hidden="true">*</span></label><input id="email" name="email" type="email" value="{{ old('email') }}" autocomplete="email" required class="field-input @error('email') field-input-error @enderror" @error('email') aria-invalid="true" aria-describedby="email_error" @enderror>@error('email')<p id="email_error" class="field-error" role="alert">{{ $message }}</p>@enderror</div>
                    <div><label for="preferred_property" class="field-label">Preferred Property <span aria-hidden="true">*</span></label><select id="preferred_property" name="preferred_property" required class="field-input @error('preferred_property') field-input-error @enderror" @error('preferred_property') aria-invalid="true" aria-describedby="preferred_property_error" @enderror><option value="">Select a model</option>@foreach (['willow' => 'The Willow', 'cedar' => 'The Cedar', 'oak' => 'The Oak', 'not_sure' => 'Not Sure Yet'] as $value => $label)<option value="{{ $value }}" @selected(old('preferred_property') === $value)>{{ $label }}</option>@endforeach</select>@error('preferred_property')<p id="preferred_property_error" class="field-error" role="alert">{{ $message }}</p>@enderror</div>
                </div>
                <div><label for="preferred_viewing_date" class="field-label">Preferred Viewing Date <span aria-hidden="true">*</span></label><input id="preferred_viewing_date" name="preferred_viewing_date" type="date" value="{{ old('preferred_viewing_date') }}" required class="field-input @error('preferred_viewing_date') field-input-error @enderror" @error('preferred_viewing_date') aria-invalid="true" aria-describedby="preferred_viewing_date_error" @enderror>@error('preferred_viewing_date')<p id="preferred_viewing_date_error" class="field-error" role="alert">{{ $message }}</p>@enderror</div>
                <div><label for="message" class="field-label">Message or Questions <span class="font-normal text-copy">(Optional)</span></label><textarea id="message" name="message" rows="4" class="field-input @error('message') field-input-error @enderror" @error('message') aria-invalid="true" aria-describedby="message_error" @enderror>{{ old('message') }}</textarea>@error('message')<p id="message_error" class="field-error" role="alert">{{ $message }}</p>@enderror</div>
                <button type="submit" class="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-primary-container px-5 py-3.5 text-sm font-semibold text-white shadow-sm transition hover:bg-secondary focus:outline-none focus-visible:ring-2 focus-visible:ring-secondary">Request a Viewing <span class="material-symbols-outlined text-lg" aria-hidden="true">calendar_month</span></button>
                <p class="text-center text-xs leading-5 text-copy">This is a portfolio demonstration form. No real viewing appointment is created.</p>
            </form>
        </div></div>
    </div>
</section>
